[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "cerulean"
ADMIN_NAME = "Twitch foods"
EXTENSIONS = [
    "delivery.ext.db:init_app",
    "delivery.ext.auth:init_app",
    "delivery.ext.admin:init_app",
    "delivery.ext.migrate:init_app",
    "delivery.ext.cli:init_app",
    "delivery.ext.site:init_app",
    "delivery.ext.hooks:init_app",
]

[development]
# O SECRET_KEY vai em um arquivo chamado .secrets.toml
DEBUG = true
SECRET_KEY = '\xf7\xb10K=\xddd\xdbZ\xd6\xd20_\xb9\xe7\x8e'
SQLALCHEMY_DATABASE_URI = "sqlite:///delivery.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
# Ele ia ver uma forma melhor de substituir o toolbar em uma posição específica
EXTENSIONS = [
    "delivery.ext.db:init_app",
    "delivery.ext.auth:init_app",
    "delivery.ext.admin:init_app",
    "delivery.ext.migrate:init_app",
    "delivery.ext.cli:init_app",
    "delivery.ext.toolbar:init_app",
    "delivery.ext.site:init_app",
    "delivery.ext.hooks:init_app",
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "mysql://...."
